#!/bin/bash	 
#$ -V				# Inherit the submission environment
#$ -cwd				# Start job in submission directory
#$ -N Milc-8			# Job Name
#$ -j y				# Combine stderr and stdout
#$ -o $JOB_NAME.o$JOB_ID	# Name of the output file (eg. myMPI.oJobID)
#$ -pe 8way 8			# Requests 16 tasks/node, 32 cores total
#$ -q normal
#$ -l h_rt=00:22:00		# Run time (hh:mm:ss) - 1.5 hours
#$ -P hpc

# Test script
~/apps/perfexpert_run_exp -o exp-8.xml ./su3_rmd
